### ISSUE TITLE
Similarities with redux-components?

### ISSUE THREAD

**Issue by markerikson** [pixellyte/redux-data-components#1]
This looks very similar to another library I've seen: https://github.com/wcjohnson/redux-components .  I'd be interested in a comparison between the two libraries - similarities, differences, use cases, etc.

**Comment by rothomas** [comment]
It has taken me a while to look closely at redux-components, and I've only been able to skim over it now.  In part, it seems to offer a similar feature set.  Here are a few points of comparison, though: 

- Obviously redux-components has been in development for a longer time, and might be more stable at this point.
- The documentation for redux-components is currently *way* better.
- The React metaphor might be more thorough in redux-components.
- The "verbs" idiom for defining internal action types in redux-components is interesting, and there's no equivalent in redux-data-components.  You still define and consume an external list of action types.
- Both feature shallow object equality comparison (===/!==) to detect changes in a component.
- Most likely the biggest practical differentiator is that redux-data-components has a heavy focus on playing well with redux-persist, something my day-job team requires.  Persisting and restoring classful objects won't work at all without specific attention.
- The approach to decorator support is sort of inverted.  Redux-components prefers decorators and offers much more developed support, with shims as a fallback.  Redux-data-components comes from the opposite direction: Decorators are an alternative, and not as well developed as a feature.
- The redux-components lifecycle methods seem to refer exclusively to mount events.  Redux-data-components also provide "update" lifecycle methods.  Redux-components might accomplish similar functionality by making components Observable, which redux-data-components does not support.
- I experimented early on with what redux-components calls "path-awareness," but ended up scrapping it for an alternate architecture: all components are declared (and referenced) in the main redux store, but their actual instances live in a separate, flat store indexed by component identifiers.  You can put references (even redundant ones) anywhere in your redux store without creating additional reduces or taking extra storage.  See the minesweeper example.  "GameMode" is exposed both at the root and as a member of "GameBoard", while "GameClock" is only mounted as a property of "GameBoard."

**Comment by rothomas** [comment]
Closing the issue, but anyone who has used redux-components (I have only browsed docs) should feel free to correct any misunderstandings.
